events { worker_connections 1024;
}

http {
    # Definice skupiny serverů, mezi které se dělí práce
    upstream my_api {
        server api:8000; # Docker DNS automaticky rozloží zátěž mezi všechny repliky 'api'
    }

    server {
        listen 80;

        location / {
            proxy_pass http://my_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}