events { worker_connections 1024;
}

http {
    # Definice skupiny serverů, mezi které se dělí práce
    upstream my_api {
        server api:8000; # Docker DNS automaticky rozloží zátěž mezi všechny repliky 'api'
    }

    server {
        listen 80;

        location /api {
            rewrite ^/api/?(.*)$ /$1 break; # Odstraňujeme prefix /api pro backend
            proxy_pass http://my_api; # Posíláme požadavky na upstream skupinu
            proxy_set_header Host $host; # Předáváme původní Host hlavi
        }

        location / {
            root /usr/share/nginx/html; # Statické soubory pro frontend
            index index.html;
        }
    }
}