# generated by datamodel-codegen:
#   filename:  https://bankaccountdata.gocardless.com/api/v2/swagger.json
#   timestamp: 2026-03-06T19:51:31+00:00

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any
from uuid import UUID
from datetime import date, datetime

from pydantic import AnyUrl, BaseModel, Field, conint, constr


class Account(BaseModel):
    id: UUID | None = Field(
        None,
        description='The ID of this Account, used to refer to this account in other API calls.',
    )
    created: datetime | None = Field(
        None, description='The date & time at which the account object was created.'
    )
    last_accessed: datetime | None = Field(
        None,
        description='The date & time at which the account object was last accessed.',
    )
    iban: str | None = Field(None, description='The Account IBAN')
    bban: str | None = Field(None, description='The Account BBAN')
    status: str | None = Field(
        None, description='The processing status of this account.'
    )
    institution_id: str | None = Field(
        None, description='The ASPSP associated with this account.'
    )
    owner_name: str | None = Field(None, description='The name of the account owner.')
    name: str | None = Field(None, description='The name of account.')


class AccountSchema(BaseModel):
    iban: str | None = Field(None, description='iban')
    bban: str | None = Field(None, description='bban')
    pan: str | None = Field(None, description='pan')
    maskedPan: str | None = Field(None, description='maskedPan')
    msisdn: str | None = Field(None, description='msisdn')
    currency: str | None = Field(None, description='currency')


class AdditionalAccountDataSchema(BaseModel):
    secondaryIdentification: str | None = Field(
        None, description='secondaryIdentification'
    )


class BalanceAmountSchema(BaseModel):
    amount: str = Field(..., description='amount')
    currency: str = Field(..., description='currency')


class BalanceSchema(BaseModel):
    balanceAmount: BalanceAmountSchema = Field(..., description='balanceAmount')
    balanceType: str = Field(..., description='balanceType')
    creditLimitIncluded: bool | None = Field(None, description='creditLimitIncluded')
    lastChangeDateTime: datetime | None = Field(None, description='lastChangeDateTime')
    referenceDate: date | None = Field(None, description='referenceDate')
    lastCommittedTransaction: str | None = Field(
        None, description='lastCommittedTransaction'
    )


class CurrencyExchangeSchema(BaseModel):
    sourceCurrency: str | None = Field(None, description='sourceCurrency')
    exchangeRate: str | None = Field(None, description='exchangeRate')
    unitCurrency: str | None = Field(None, description='unitCurrency')
    targetCurrency: str | None = Field(None, description='targetCurrency')
    quotationDate: date | None = Field(None, description='quotationDate')
    contractIdentification: str | None = Field(
        None, description='contractIdentification'
    )


class EndUserAgreement(BaseModel):
    id: UUID | None = Field(
        None,
        description='The ID of this End User Agreement, used to refer to this end user agreement in other API calls.',
        title='End User Agreement ID',
    )
    created: datetime | None = Field(
        None,
        description='The date & time at which the end user agreement was created.',
        title='Created Date',
    )
    institution_id: str = Field(..., description='an Institution ID for this EUA')
    max_historical_days: conint(ge=1, le=730) | None = Field(
        90,
        description='Maximum number of days of transaction data to retrieve.',
        title='Maximum Historical Days',
    )
    access_valid_for_days: conint(ge=1, le=730) | None = Field(
        90,
        description='Number of days from acceptance that the access can be used.',
        title='Access Valid For (Days)',
    )
    access_scope: list[Any] | None = Field(
        ['balances', 'details', 'transactions'],
        description="Array containing one or several values of ['balances', 'details', 'transactions']",
        title='Level of information to access (by default all)',
    )
    accepted: datetime | None = Field(
        None,
        description='The date & time at which the end user accepted the agreement.',
        title='Accepted Date',
    )
    reconfirmation: bool | None = Field(
        False,
        description='if this agreement can be extended. Supported by GB banks only.',
    )


class EndUserAgreementRequest(BaseModel):
    institution_id: constr(min_length=1) = Field(
        ..., description='an Institution ID for this EUA'
    )
    max_historical_days: conint(ge=1, le=730) | None = Field(
        90,
        description='Maximum number of days of transaction data to retrieve.',
        title='Maximum Historical Days',
    )
    access_valid_for_days: conint(ge=1, le=730) | None = Field(
        90,
        description='Number of days from acceptance that the access can be used.',
        title='Access Valid For (Days)',
    )
    access_scope: list[Any] | None = Field(
        ['balances', 'details', 'transactions'],
        description="Array containing one or several values of ['balances', 'details', 'transactions']",
        title='Level of information to access (by default all)',
    )
    reconfirmation: bool | None = Field(
        False,
        description='if this agreement can be extended. Supported by GB banks only.',
    )


class EnduserAcceptanceDetailsRequest(BaseModel):
    user_agent: constr(min_length=1) = Field(
        ..., title='user agent string for the end user'
    )
    ip_address: constr(min_length=1) = Field(..., title='end user IP address')


class ErrorResponse(BaseModel):
    summary: str
    detail: str
    type: str | None = None
    status_code: int


class Integration(BaseModel):
    id: str
    name: str
    bic: str | None = None
    transaction_total_days: str | None = '90'
    max_access_valid_for_days: str | None = None
    max_access_valid_for_days_reconfirmation: str | None = None
    countries: list[str]
    logo: str


class IntegrationRetrieve(BaseModel):
    id: str
    name: str
    bic: str | None = None
    transaction_total_days: str | None = '90'
    max_access_valid_for_days: str | None = None
    max_access_valid_for_days_reconfirmation: str | None = None
    countries: list[str]
    logo: str
    supported_features: list[Any]
    identification_codes: list[Any]


class JWTObtainPairRequest(BaseModel):
    secret_id: constr(min_length=1) = Field(
        ..., description='Secret id from /user-secrets/'
    )
    secret_key: constr(min_length=1) = Field(
        ..., description='Secret key from /user-secrets/'
    )


class JWTRefreshRequest(BaseModel):
    refresh: constr(min_length=1)


class OwnerAddressStructuredSchema(BaseModel):
    streetName: str | None = Field(None, description='streetName')
    buildingNumber: str | None = Field(None, description='buildingNumber')
    townName: str | None = Field(None, description='townName')
    postCode: str | None = Field(None, description='postCode')
    country: str | None = Field(None, description='country')


class PaginatedEndUserAgreementList(BaseModel):
    count: int = Field(..., example=123)
    next: AnyUrl | None = Field(
        None,
        example='https://bankaccountdata.gocardless.com/api/v2/agreements/enduser/?limit=100&offset=0',
    )
    previous: AnyUrl | None = Field(
        None,
        example='https://bankaccountdata.gocardless.com/api/v2/agreements/enduser/?limit=100&offset=0',
    )
    results: list[EndUserAgreement]


class ReconfirmationRetrieve(BaseModel):
    reconfirmation_url: AnyUrl | None = Field(
        None, description='Reconfirmation URL to be provided to PSU.'
    )
    created: datetime | None = Field(None, description='Reconfirmation creation time')
    url_valid_from: datetime | None = Field(
        None,
        description='Datetime from when PSU will be able to access reconfirmation URL.',
    )
    url_valid_to: datetime | None = Field(
        None,
        description='Datetime until when PSU will be able to access reconfirmation URL.',
    )
    redirect: AnyUrl | None = Field(
        None,
        description="Optional redirect URL for reconfirmation to override requisition's redirect.",
        title='redirect_url',
    )
    last_accessed: datetime | None = Field(
        None,
        description='Last time when reconfirmation was accessed (this does not mean that it was accessed by PSU).',
    )
    last_submitted: datetime | None = Field(
        None,
        description='Last time reconfirmation was submitted (it can be submitted multiple times).',
    )
    accounts: dict[str, Any] | None = Field(
        None,
        description='Dictionary of accounts and their reconfirm and reject timestamps',
        example={
            '64a985ae-4427-4a27-bd36-fd625fe6e1fc': {
                'reconfirmed': '2025-01-14T15:20:56.942817Z',
                'rejected': '',
            },
            'cd2fbd71-15f7-4607-bea2-fbd80311a013': {'reconfirmed': '', 'rejected': ''},
        },
    )


class ReconfirmationRetrieveRequest(BaseModel):
    redirect: AnyUrl | None = Field(
        None,
        description="Optional redirect URL for reconfirmation to override requisition's redirect.",
        title='redirect_url',
    )


class RequisitionRequest(BaseModel):
    redirect: AnyUrl = Field(
        ...,
        description='redirect URL to your application after end-user authorization with ASPSP',
    )
    institution_id: constr(min_length=1) = Field(
        ..., description='an Institution ID for this Requisition'
    )
    agreement: UUID | None = Field(
        None, description='EUA associated with this requisition'
    )
    reference: constr(min_length=1, max_length=256) | None = Field(
        None, description='additional ID to identify the end user'
    )
    user_language: constr(min_length=1, max_length=5) | None = Field(
        None, description='A two-letter country code (ISO 639-1)'
    )
    ssn: constr(max_length=64) | None = Field(
        None, description='optional SSN field to verify ownership of the account'
    )
    account_selection: bool | None = Field(
        False, description='option to enable account selection view for the end user'
    )
    redirect_immediate: bool | None = Field(
        False,
        description='enable redirect back to the client after account list received',
    )


class SpectacularJWTObtain(BaseModel):
    access: str | None = Field(None, description='Your access token')
    access_expires: int | None = Field(
        86400, description='Access token expires in seconds'
    )
    refresh: str | None = Field(None, description='Your refresh token')
    refresh_expires: int | None = Field(
        2592000, description='Refresh token expires in seconds'
    )


class SpectacularJWTRefresh(BaseModel):
    access: str | None = Field(None, description='Your access token')
    access_expires: int | None = Field(
        86400, description='Access token expires in seconds'
    )


class StatusEnum(StrEnum):
    CR = 'CR'
    ID = 'ID'
    LN = 'LN'
    RJ = 'RJ'
    ER = 'ER'
    SU = 'SU'
    EX = 'EX'
    GC = 'GC'
    UA = 'UA'
    GA = 'GA'
    SA = 'SA'
    CZ = 'CZ'


class SuccessfulDeleteResponse(BaseModel):
    summary: str
    detail: str


class TransactionAmountSchema(BaseModel):
    amount: str = Field(..., description='amount')
    currency: str = Field(..., description='currency')


class AccountBalance(BaseModel):
    balances: list[BalanceSchema] | None = None


class BalanceAfterTransactionSchema(BaseModel):
    balanceAmount: TransactionAmountSchema = Field(..., description='balanceAmount')
    balanceType: str = Field(..., description='balanceType')


class DetailSchema(BaseModel):
    resourceId: str | None = Field(None, description='resourceId')
    iban: str | None = Field(None, description='iban')
    bban: str | None = Field(None, description='bban')
    scan: str | None = Field(
        None,
        description='SortCodeAccountNumber returned by some UK banks (6 digit Sort Code and 8 digit Account Number)',
    )
    msisdn: str | None = Field(None, description='msisdn')
    currency: str | None = Field(None, description='currency')
    ownerName: str | None = Field(None, description='ownerName')
    name: str | None = Field(None, description='name')
    displayName: str | None = Field(None, description='displayName')
    product: str | None = Field(None, description='product')
    cashAccountType: str | None = Field(None, description='cashAccountType')
    status: str | None = Field(None, description='status')
    bic: str | None = Field(None, description='bic')
    linkedAccounts: str | None = Field(None, description='linkedAccounts')
    maskedPan: str | None = Field(None, description='maskedPan')
    usage: str | None = Field(None, description='usage')
    details: str | None = Field(None, description='details')
    ownerAddressUnstructured: list[str] | None = Field(
        None, description='ownerAddressUnstructured'
    )
    ownerAddressStructured: OwnerAddressStructuredSchema | None = Field(
        None, description='ownerAddressStructured'
    )
    additionalAccountData: AdditionalAccountDataSchema | None = Field(
        None,
        description='additionalAccountData used for information that is outside of Berlin Group specification, such as bank or country-specific fields',
    )


class Requisition(BaseModel):
    id: UUID | None = None
    created: datetime | None = Field(
        None,
        description='The date & time at which the requisition was created.',
        title='Created Date',
    )
    redirect: AnyUrl = Field(
        ...,
        description='redirect URL to your application after end-user authorization with ASPSP',
    )
    status: StatusEnum | None = Field(
        None, description='status of this requisition', title='Requisition status'
    )
    institution_id: str = Field(
        ..., description='an Institution ID for this Requisition'
    )
    agreement: UUID | None = Field(
        None, description='EUA associated with this requisition'
    )
    reference: constr(max_length=256) | None = Field(
        None, description='additional ID to identify the end user'
    )
    accounts: list[UUID] | None = Field(
        None,
        description='array of account IDs retrieved within a scope of this requisition',
    )
    user_language: constr(max_length=5) | None = Field(
        None, description='A two-letter country code (ISO 639-1)'
    )
    link: AnyUrl | None = Field(
        'https://ob.gocardless.com/psd2/start/3fa85f64-5717-4562-b3fc-2c963f66afa6/SANDBOXFINANCE_SFIN0000',
        description='link to initiate authorization with Institution',
    )
    ssn: constr(max_length=64) | None = Field(
        None, description='optional SSN field to verify ownership of the account'
    )
    account_selection: bool | None = Field(
        False, description='option to enable account selection view for the end user'
    )
    redirect_immediate: bool | None = Field(
        False,
        description='enable redirect back to the client after account list received',
    )


class SpectacularRequisition(BaseModel):
    id: UUID | None = None
    created: datetime | None = Field(
        None,
        description='The date & time at which the requisition was created.',
        title='Created Date',
    )
    redirect: AnyUrl = Field(
        ...,
        description='redirect URL to your application after end-user authorization with ASPSP',
    )
    status: StatusEnum | None = Field(
        None, description='status of this requisition', title='Requisition status'
    )
    institution_id: str = Field(
        ..., description='an Institution ID for this Requisition'
    )
    agreement: UUID | None = Field(
        None, description='EUA associated with this requisition'
    )
    reference: constr(max_length=256) | None = Field(
        None, description='additional ID to identify the end user'
    )
    accounts: list[Any] | None = Field(
        [],
        description='array of account IDs retrieved within a scope of this requisition',
    )
    user_language: constr(max_length=5) | None = Field(
        None, description='A two-letter country code (ISO 639-1)'
    )
    link: AnyUrl | None = Field(
        'https://ob.gocardless.com/psd2/start/3fa85f64-5717-4562-b3fc-2c963f66afa6/SANDBOXFINANCE_SFIN0000',
        description='link to initiate authorization with Institution',
    )
    ssn: constr(max_length=64) | None = Field(
        None, description='optional SSN field to verify ownership of the account'
    )
    account_selection: bool | None = Field(
        False, description='option to enable account selection view for the end user'
    )
    redirect_immediate: bool | None = Field(
        False,
        description='enable redirect back to the client after account list received',
    )


class TransactionSchema(BaseModel):
    transactionId: str | None = Field(None, description='transactionId')
    entryReference: str | None = Field(None, description='entryReference')
    endToEndId: str | None = Field(None, description='endToEndId')
    mandateId: str | None = Field(None, description='mandateId')
    checkId: str | None = Field(None, description='checkId')
    creditorId: str | None = Field(None, description='creditorId')
    bookingDate: date | None = Field(None, description='bookingDate')
    valueDate: date | None = Field(None, description='valueDate')
    bookingDateTime: datetime | None = Field(None, description='bookingDateTime')
    valueDateTime: datetime | None = Field(None, description='valueDateTime')
    transactionAmount: TransactionAmountSchema = Field(
        ..., description='transactionAmount'
    )
    currencyExchange: list[CurrencyExchangeSchema] | None = None
    creditorName: str | None = Field(None, description='creditorName')
    creditorAccount: AccountSchema | None = Field(None, description='creditorAccount')
    ultimateCreditor: str | None = Field(None, description='ultimateCreditor')
    debtorName: str | None = Field(None, description='debtorName')
    debtorAccount: AccountSchema | None = Field(None, description='debtorAccount')
    ultimateDebtor: str | None = Field(None, description='ultimateDebtor')
    remittanceInformationUnstructured: str | None = Field(
        None, description='remittanceInformationUnstructured'
    )
    remittanceInformationUnstructuredArray: list[str] | None = Field(
        None, description='remittanceInformationUnstructuredArray'
    )
    remittanceInformationStructured: str | None = Field(
        None, description='remittanceInformationStructured'
    )
    remittanceInformationStructuredArray: list[str] | None = Field(
        None, description='remittanceInformationStructuredArray'
    )
    additionalInformation: str | None = Field(None, description='additionalInformation')
    purposeCode: str | None = Field(None, description='purposeCode')
    bankTransactionCode: str | None = Field(None, description='bankTransactionCode')
    proprietaryBankTransactionCode: str | None = Field(
        None, description='proprietaryBankTransactionCode'
    )
    internalTransactionId: str | None = Field(None, description='internalTransactionId')
    balanceAfterTransaction: BalanceAfterTransactionSchema | None = Field(
        None, description='balanceAfterTransaction'
    )


class AccountDetail(BaseModel):
    account: DetailSchema = Field(..., description='account')


class BankTransaction(BaseModel):
    booked: list[TransactionSchema]
    pending: list[TransactionSchema] | None = None


class PaginatedRequisitionList(BaseModel):
    count: int = Field(..., example=123)
    next: AnyUrl | None = Field(
        None,
        example='https://bankaccountdata.gocardless.com/api/v2/requisitions/?limit=100&offset=0',
    )
    previous: AnyUrl | None = Field(
        None,
        example='https://bankaccountdata.gocardless.com/api/v2/requisitions/?limit=100&offset=0',
    )
    results: list[Requisition]


class AccountTransactions(BaseModel):
    transactions: BankTransaction = Field(..., description='transactions')
    last_updated: datetime | None = Field(
        None, description='The last time the account transactions were updated'
    )
