name: Test budget app 

on:
  pull_request:
    branches:
      - main   # Spustí se jen při pull request do main
    paths:
      - 'backend/**'  # Spustí se jen pokud se změní něco v backendu
      - 'frontend/**'  # Spustí se jen pokud se změní něco ve frontendu

jobs:
  test-be: #Říká, na jakém stroji pipeline poběží.
    runs-on: ubuntu-latest #= virtuální Ubuntu mašina na serverech GitHubu. Standard. Nic řešit.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 #Stáhne kód z repozitáře na ten virtuální stroj.

      # --- TADY JE TEN TEST ---
      - name: Set up Python #Nastaví verzi Pythonu.
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install flake8 #Nastaví Python 3.12, nainstaluje flake8.
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Linting (Simple Test) #Spustí kontrolu kódu.
        #Tohle je ten "test". Flake8 je linter — kontroluje kód na chyby. Ale pozor: tenhle příkaz kontroluje jen syntaktické chyby a nedefinované proměnné (kódy E9, F63, F7, F82).
        #Nekontroluje logiku, netestuje funkčnost. Je to minimum, ale lepší než nic — zachytí situace, kdy bys deployoval kód, který se ani nespustí.
        run: |
          cd backend
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics  
  test-fe: #Říká, na jakém stroji pipeline poběží.
    runs-on: ubuntu-latest #= virtuální Ubuntu mašina na serverech GitHubu. Standard. Nic řešit.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 #Stáhne kód z repozitáře na ten virtuální stroj.

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run Linting (ESLint)
        run: |
          cd frontend
          # Tohle ověří, že v JS/TS nemáš boty, než začneš buildovat
          npm run lint 