name: Deploy Backend to Azure #Jméno workflow. Zobrazí se v záložce Actions na GitHubu. Jen kosmetika

on:
  push:
    branches:
      - main   # Spustí se jen při pushi do main
    paths:
      - 'backend/**'  # Spustí se jen pokud se změní něco v backendu
  workflow_dispatch: # Přidá tlačítko pro manuální spuštění v GitHubu

jobs:
  build-and-deploy: #Říká, na jakém stroji pipeline poběží.
    runs-on: ubuntu-latest #= virtuální Ubuntu mašina na serverech GitHubu. Standard. Nic řešit.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 #Stáhne kód z repozitáře na ten virtuální stroj.

      - name: Log in to Azure #Přihlášení k Azure
        uses: azure/login@v2 #Používá akci "login" verze 2 od Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} #Přihlašovací údaje k Azure, užene do v Github secrets, šifrované!

      - name: Log in to ACR #Přihlásí se do Azure Container Registry (ACR) — to je soukromý Docker Hub na Azure, kde budeš ukládat Docker image.
        uses: azure/docker-login@v1 #Používá akci "docker-login" verze 1 od Azure
        with: #Přihlašovací údaje k Azure Container Registry, užene do v Github secrets, šifrované!
          login-server: ${{ secrets.AZURE_REGISTRY_SERVER }} 
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push Docker image #Sestaví Docker image z tvého backendu a nahraje ho do ACR. 
        #Všimni si tagu ${{ github.sha }} — každý build dostane unikátní tag podle hash commitu. Takže vždy víš, jaký kód je kde deployovaný. Tohle je správná praxe.
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_SERVER }}/budget-backend:${{ github.sha }} ./backend
          docker push ${{ secrets.AZURE_REGISTRY_SERVER }}/budget-backend:${{ github.sha }}

      - name: Deploy to Azure Container App #Nasadí novou verzi do Azure Container App. 
        uses: azure/container-apps-deploy-action@v1 #Používá akci "container-apps-deploy-action" verze 1 od Azure
        with: 
          containerAppName: budget-api #Jméno tvé Container App v Azure.
          resourceGroup: budget-app-rg #Jméno resource groupu v Azure.
          imageToDeploy: ${{ secrets.AZURE_REGISTRY_SERVER }}/budget-backend:${{ github.sha }} #Image, který se má nasadit.
          targetPort: 8000 #Port, na kterém běží aplikace uvnitř kontejneru.
          ingress: external #Povolí externí přístup k aplikaci.